// Mock data for testing when backend API is not available
export const mockNotes = [
  {
    note_id: "64f1a2b3c4d5e6f7g8h9i0j1",
    xsec_token: "XYZ123ABC456DEF789",
    type: "normal" as const,
    title: "新手妈妈必看！宝宝保险怎么选？我的踩坑经验分享",
    liked_count: 1248,
    cover: "/placeholder.svg?height=300&width=400",
    user_id: "user_mom_2024",
    user_name: "小雨妈妈",
    user_xsec_token: "USER_TOKEN_123",
  },
  {
    note_id: "64f1a2b3c4d5e6f7g8h9i0j2",
    xsec_token: "XYZ123ABC456DEF790",
    type: "video" as const,
    title: "30岁买什么保险最划算？理财规划师告诉你",
    liked_count: 892,
    cover: "/placeholder.svg?height=300&width=400",
    user_id: "user_planner_pro",
    user_name: "理财小助手",
    user_xsec_token: "USER_TOKEN_124",
  },
  {
    note_id: "64f1a2b3c4d5e6f7g8h9i0j3",
    xsec_token: "XYZ123ABC456DEF791",
    type: "normal" as const,
    title: "医疗险vs重疾险，到底该买哪个？详细对比来了",
    liked_count: 2156,
    cover: "/placeholder.svg?height=300&width=400",
    user_id: "user_insurance_expert",
    user_name: "保险小白兔",
    user_xsec_token: "USER_TOKEN_125",
  },
]

export const mockComments = [
  {
    id: "comment_001",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j1",
    content: "我家宝宝刚出生，正在纠结要不要买保险，看了你的分享很有用！请问有推荐的保险公司吗？预算大概5000左右",
    user_id: "new_mom_2024",
    user_name: "新手妈妈小李",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 23,
    created_time: "2024-01-15T10:30:00Z",
    note_title: "新手妈妈必看！宝宝保险怎么选？我的踩坑经验分享",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j1",
    note_type: "normal" as const,
  },
  {
    id: "comment_002",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j1",
    content: "太实用了！我之前买保险就是没做功课，买了很多不必要的。现在想给二胎宝宝重新规划一下，能私信咨询吗？",
    user_id: "experienced_mom",
    user_name: "二胎妈妈王女士",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 15,
    created_time: "2024-01-15T14:20:00Z",
    note_title: "新手妈妈必看！宝宝保险怎么选？我的踩坑经验分享",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j1",
    note_type: "normal" as const,
  },
  {
    id: "comment_003",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j2",
    content: "30岁了还没买保险，看了视频觉得很焦虑。想问下重疾险和医疗险哪个更重要？月收入8000应该怎么配置？",
    user_id: "young_professional",
    user_name: "职场新人小张",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 31,
    created_time: "2024-01-16T09:15:00Z",
    note_title: "30岁买什么保险最划算？理财规划师告诉你",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j2",
    note_type: "video" as const,
  },
  {
    id: "comment_004",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j2",
    content: "刚好30岁，正在考虑买保险。家里有房贷车贷，压力很大，但是又担心生病没保障。求推荐性价比高的产品！",
    user_id: "mortgage_holder",
    user_name: "有房贷的小陈",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 18,
    created_time: "2024-01-16T16:45:00Z",
    note_title: "30岁买什么保险最划算？理财规划师告诉你",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j2",
    note_type: "video" as const,
  },
  {
    id: "comment_005",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j3",
    content: "医疗险和重疾险的区别终于搞清楚了！我想两个都买，但是预算有限，能推荐一些便宜但保障全面的产品吗？",
    user_id: "budget_conscious",
    user_name: "精打细算的小王",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 27,
    created_time: "2024-01-17T11:30:00Z",
    note_title: "医疗险vs重疾险，到底该买哪个？详细对比来了",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j3",
    note_type: "normal" as const,
  },
  {
    id: "comment_006",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j3",
    content: "家里老人身体不太好，想给他们买医疗险，但是年龄大了很多产品都买不了。有什么好的建议吗？急需！",
    user_id: "caring_child",
    user_name: "孝顺女儿小刘",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 42,
    created_time: "2024-01-17T19:20:00Z",
    note_title: "医疗险vs重疾险，到底该买哪个？详细对比来了",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j3",
    note_type: "normal" as const,
  },
  {
    id: "comment_007",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j1",
    content: "刚怀孕，正在研究宝宝保险。看了好多攻略还是很迷茫，能加微信详细咨询吗？愿意付费咨询！",
    user_id: "pregnant_mom",
    user_name: "准妈妈小赵",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 8,
    created_time: "2024-01-18T08:45:00Z",
    note_title: "新手妈妈必看！宝宝保险怎么选？我的踩坑经验分享",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j1",
    note_type: "normal" as const,
  },
  {
    id: "comment_008",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j2",
    content: "自己开公司，没有社保，想买商业保险做保障。看了你的分析很专业，能推荐适合创业者的保险方案吗？",
    user_id: "entrepreneur",
    user_name: "创业者老板",
    user_avatar: "/placeholder.svg?height=40&width=40",
    liked_count: 35,
    created_time: "2024-01-18T13:10:00Z",
    note_title: "30岁买什么保险最划算？理财规划师告诉你",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j2",
    note_type: "video" as const,
  },
]

export const mockAnalyzedLeads = [
  {
    user_id: "new_mom_2024",
    user_name: "新手妈妈小李",
    user_avatar: "/placeholder.svg?height=40&width=40",
    id: "comment_001",
    content: "我家宝宝刚出生，正在纠结要不要买保险，看了你的分享很有用！请问有推荐的保险公司吗？预算大概5000左右",
    liked_count: 23,
    created_time: "2024-01-15T10:30:00Z",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j1",
    note_title: "新手妈妈必看！宝宝保险怎么选？我的踩坑经验分享",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j1",
    note_type: "normal" as const,
    note_cover: "/placeholder.svg?height=300&width=400",
    note_liked_count: 1248,
    aiAnalysis:
      "这是一个高质量的潜在客户。用户明确表达了购买需求（新生儿保险），有具体的预算范围（5000元），并且主动寻求专业建议。作为新手妈妈，她对保险产品的需求紧迫且明确，购买决策时机成熟。建议重点推荐少儿重疾险和医疗险组合产品。",
    leadScore: 92,
    tags: ["新生儿保险", "预算明确", "主动咨询", "高购买意向", "新手妈妈"],
    engagement: "活跃用户",
    intentLevel: "极高",
    contactPotential: "高",
  },
  {
    user_id: "young_professional",
    user_name: "职场新人小张",
    user_avatar: "/placeholder.svg?height=40&width=40",
    id: "comment_003",
    content: "30岁了还没买保险，看了视频觉得很焦虑。想问下重疾险和医疗险哪个更重要？月收入8000应该怎么配置？",
    liked_count: 31,
    created_time: "2024-01-16T09:15:00Z",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j2",
    note_title: "30岁买什么保险最划算？理财规划师告诉你",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j2",
    note_type: "video" as const,
    note_cover: "/placeholder.svg?height=300&width=400",
    note_liked_count: 892,
    aiAnalysis:
      "优质潜在客户，表现出强烈的购买焦虑和紧迫感。用户30岁正值保险购买黄金期，有稳定收入（8000/月），主动询问产品配置建议。焦虑情绪表明购买意愿强烈，是成交概率很高的目标客户。建议推荐重疾险+医疗险的组合方案。",
    leadScore: 88,
    tags: ["30岁黄金期", "收入稳定", "购买焦虑", "产品咨询", "配置需求"],
    engagement: "高活跃",
    intentLevel: "极高",
    contactPotential: "高",
  },
  {
    user_id: "mortgage_holder",
    user_name: "有房贷的小陈",
    user_avatar: "/placeholder.svg?height=40&width=40",
    id: "comment_004",
    content: "刚好30岁，正在考虑买保险。家里有房贷车贷，压力很大，但是又担心生病没保障。求推荐性价比高的产品！",
    liked_count: 18,
    created_time: "2024-01-16T16:45:00Z",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j2",
    note_title: "30岁买什么保险最划算？理财规划师告诉你",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j2",
    note_type: "video" as const,
    note_cover: "/placeholder.svg?height=300&width=400",
    note_liked_count: 892,
    aiAnalysis:
      "高价值潜在客户。用户有明确的风险意识和保障需求，虽然经济压力大但正是需要保险保障的典型场景。有房贷车贷说明有一定经济基础，对性价比敏感表明是理性消费者。建议推荐定期寿险+重疾险的经济型组合。",
    leadScore: 85,
    tags: ["房贷车贷", "风险意识强", "性价比敏感", "经济压力", "保障需求"],
    engagement: "中等活跃",
    intentLevel: "高",
    contactPotential: "中",
  },
  {
    user_id: "caring_child",
    user_name: "孝顺女儿小刘",
    user_avatar: "/placeholder.svg?height=40&width=40",
    id: "comment_006",
    content: "家里老人身体不太好，想给他们买医疗险，但是年龄大了很多产品都买不了。有什么好的建议吗？急需！",
    liked_count: 42,
    created_time: "2024-01-17T19:20:00Z",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j3",
    note_title: "医疗险vs重疾险，到底该买哪个？详细对比来了",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j3",
    note_type: "normal" as const,
    note_cover: "/placeholder.svg?height=300&width=400",
    note_liked_count: 2156,
    aiAnalysis:
      "紧急需求客户，购买意向极其强烈。用户为父母健康担忧，有明确的产品需求（老人医疗险），使用'急需'表明时间紧迫性。虽然老人投保有限制，但正是专业保险顾问发挥价值的场景。建议推荐防癌险或老人专属医疗险产品。",
    leadScore: 90,
    tags: ["老人保险", "急需产品", "孝心消费", "专业需求", "时间紧迫"],
    engagement: "高活跃",
    intentLevel: "极高",
    contactPotential: "高",
  },
  {
    user_id: "pregnant_mom",
    user_name: "准妈妈小赵",
    user_avatar: "/placeholder.svg?height=40&width=40",
    id: "comment_007",
    content: "刚怀孕，正在研究宝宝保险。看了好多攻略还是很迷茫，能加微信详细咨询吗？愿意付费咨询！",
    liked_count: 8,
    created_time: "2024-01-18T08:45:00Z",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j1",
    note_title: "新手妈妈必看！宝宝保险怎么选？我的踩坑经验分享",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j1",
    note_type: "normal" as const,
    note_cover: "/placeholder.svg?height=300&width=400",
    note_liked_count: 1248,
    aiAnalysis:
      "超高质量潜在客户。用户主动要求付费咨询，表明极强的购买意愿和支付能力。怀孕期间为宝宝规划保险体现了强烈的责任感和前瞻性。主动要求加微信说明愿意建立深度联系，是最容易转化的客户类型。",
    leadScore: 95,
    tags: ["付费咨询", "怀孕期", "主动联系", "超高意向", "深度需求"],
    engagement: "新用户",
    intentLevel: "极高",
    contactPotential: "高",
  },
  {
    user_id: "entrepreneur",
    user_name: "创业者老板",
    user_avatar: "/placeholder.svg?height=40&width=40",
    id: "comment_008",
    content: "自己开公司，没有社保，想买商业保险做保障。看了你的分析很专业，能推荐适合创业者的保险方案吗？",
    liked_count: 35,
    created_time: "2024-01-18T13:10:00Z",
    note_id: "64f1a2b3c4d5e6f7g8h9i0j2",
    note_title: "30岁买什么保险最划算？理财规划师告诉你",
    note_url: "https://www.xiaohongshu.com/explore/64f1a2b3c4d5e6f7g8h9i0j2",
    note_type: "video" as const,
    note_cover: "/placeholder.svg?height=300&width=400",
    note_liked_count: 892,
    aiAnalysis:
      "高价值商业客户。创业者通常收入较高且风险意识强，没有社保使得商业保险需求更加迫切。认可专业分析表明对服务质量有要求，愿意为专业服务付费。建议推荐高保额的重疾险+医疗险+意外险全面保障方案。",
    leadScore: 87,
    tags: ["创业者", "无社保", "高收入潜力", "专业认可", "全面保障"],
    engagement: "高活跃",
    intentLevel: "高",
    contactPotential: "高",
  },
]

export const mockSummary = {
  totalAnalyzed: 8,
  highQualityLeads: 6,
  averageScore: 89,
  topKeywords: ["宝宝保险", "重疾险", "医疗险", "30岁保险", "性价比"],
  scrapingStatus: "成功分析 3 个笔记，8 条真实评论",
  notesAnalyzed: 3,
}

// Helper function to simulate API delay
export const simulateApiDelay = (ms = 2000) => {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

// Mock API responses
export const mockApiResponses = {
  searchNotes: async (keyword: string) => {
    await simulateApiDelay(1500)
    return mockNotes.filter(
      (note) => note.title.includes(keyword) || keyword.includes("保险") || keyword.includes("宝宝"),
    )
  },

  getNoteComments: async (noteId: string) => {
    await simulateApiDelay(1000)
    return mockComments.filter((comment) => comment.note_id === noteId)
  },

  analyzeLeads: async (keyword: string) => {
    await simulateApiDelay(3000)
    return {
      leads: mockAnalyzedLeads,
      summary: mockSummary,
    }
  },
}
